import { TrafficSign } from '@/types/game';
import { splitSigns } from '@/lib/signList';

/**
 * Sign images are bundled locally (public/signs/<id>.png) so the game works
 * offline and doesn't depend on a third-party server.
 * Source: Transportstyrelsen's official sign graphics (treated as public domain,
 * credit: Transportstyrelsen). E1 is Wikimedia Commons "Sweden road sign E1"
 * (public domain), because the official URL for it returns 404.
 */
const signImage = (id: string) => `${import.meta.env.BASE_URL}signs/${id.toLowerCase()}.png`;

/**
 * Swedish traffic signs — codes, names and descriptions verified against
 * Transportstyrelsen (TSFS 2019:74) and Vägmärkesförordningen (SFS 2007:90).
 * Official PNG images are bundled with the app (see signImage).
 *
 * ALL_SIGNS is the full data list. The app reads TRAFFIC_SIGNS (below), which leaves out signs flagged
 * `placeholder: true` (texts entered, official image still missing). To finish one: add public/signs/<id>.png
 * + `imageUrl: signImage('<id>')`, then delete the flag. Only the data-integrity test reads ALL_SIGNS.
 */
export const ALL_SIGNS: TrafficSign[] = [

  // ── A. VARNINGSMÄRKEN (Warning signs) ─────────────────────────────
  {
    id: 'A1', code: 'A1',
    name: 'Varning för farlig kurva',
    nameEn: 'Dangerous curve ahead',
    nameAr: 'منعطف خطِر',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '↷',
    imageUrl: signImage('A1'),
    description: 'Varnar för en skarp eller smal kurva som kräver nedsatt hastighet.',
    descriptionEn: 'Warns of a sharp or narrow curve that calls for reduced speed.',
    descriptionAr: 'تحذير من منعطف خطير حاد أو ضيق يستوجب خفض السرعة.',
  },
  {
    id: 'A2', code: 'A2',
    name: 'Varning för flera farliga kurvor',
    nameEn: 'Series of dangerous curves',
    nameAr: 'منعطفات خطِرة متتالية',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '↶↷',
    imageUrl: signImage('A2'),
    description: 'Anger flera farliga kurvor i rad. Den första kurvans riktning visas av motivet.',
    descriptionEn: 'Indicates several dangerous curves in a row. The symbol shows the direction of the first curve.',
    descriptionAr: 'تحذير من تعاقب عدة منعطفات خطيرة. يشير الرمز إلى اتجاه المنعطف الأول.',
  },
  {
    id: 'A5', code: 'A5',
    name: 'Varning för avsmalnande väg',
    nameEn: 'Road narrows ahead',
    nameAr: 'طريق يضيق',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '⇕',
    imageUrl: signImage('A5'),
    description: 'Vägen smalnar av framåt. Iaktta försiktighet och håll hastigheten nere.',
    descriptionEn: 'The road narrows ahead. Be careful and keep your speed down.',
    descriptionAr: 'الطريق يضيق أمامك. انتبه وخفّف سرعتك.',
  },
  {
    id: 'A8', code: 'A8',
    name: 'Varning för ojämn väg',
    nameEn: 'Uneven road surface',
    nameAr: 'طريق غير مستوٍ',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '〰',
    imageUrl: signImage('A8'),
    description: 'Vägen har gropar, gupp eller annat ojämnt underlag som kan påverka fordonets kontroll.',
    descriptionEn: 'The road has potholes, bumps or other uneven surface that can affect vehicle control.',
    descriptionAr: 'الطريق فيه حفر أو نتوءات تؤثر على التحكم بالمركبة.',
  },
  {
    id: 'A9', code: 'A9',
    name: 'Varning för farthinder',
    nameEn: 'Speed bump ahead',
    nameAr: 'مطبّ سرعة',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '⌒',
    imageUrl: signImage('A9'),
    description: 'Varnar för ett avsiktligt anlagt gupp i körbanan avsett att dämpa hastigheten.',
    descriptionEn: 'Warns of a deliberately built bump in the roadway meant to slow traffic down.',
    descriptionAr: 'تحذير من مطبّ مقصود لتهدئة السرعة.',
  },
  {
    id: 'A10', code: 'A10',
    name: 'Varning för slirig väg',
    nameEn: 'Slippery road surface',
    nameAr: 'طريق زلق',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '💧',
    imageUrl: signImage('A10'),
    description: 'Vägen kan vara hal på grund av regn, is, snö eller löst grus. Sänk hastigheten.',
    descriptionEn: 'The road may be slippery because of rain, ice, snow or loose gravel. Reduce speed.',
    descriptionAr: 'الطريق قد يكون زلقاً بسبب المطر أو الجليد أو الثلج. خفّف السرعة.',
  },
  {
    id: 'A12', code: 'A12',
    name: 'Varning för stenras',
    nameEn: 'Falling rocks',
    nameAr: 'خطر تساقط الصخور',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🪨',
    imageUrl: signImage('A12'),
    description: 'Risk för stenras. Stenar kan ligga på eller rulla ned på vägen från omgivande sluttningar.',
    descriptionEn: 'Risk of falling rocks. Stones may lie on or roll down onto the road from the surrounding slopes.',
    descriptionAr: 'خطر سقوط الحجارة من المنحدرات المحيطة على الطريق.',
  },
  {
    id: 'A13', code: 'A13',
    name: 'Varning för övergångsställe',
    nameEn: 'Pedestrian crossing ahead',
    nameAr: 'معبر مشاة أمامك',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚶',
    imageUrl: signImage('A13'),
    description: 'Varnar för ett obevakat övergångsställe där fotgängare har företräde.',
    descriptionEn: 'Warns of an unsupervised pedestrian crossing where pedestrians have priority.',
    descriptionAr: 'تحذير من معبر مشاة غير مراقَب حيث للمشاة الأولوية.',
  },
  {
    id: 'A14', code: 'A14',
    name: 'Varning för gående',
    nameEn: 'Pedestrians in road',
    nameAr: 'مشاة على الطريق',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚶',
    imageUrl: signImage('A14'),
    description: 'Gående befinner sig eller kan befinna sig på eller nära körbanan utan avgränsat övergångsställe.',
    descriptionEn: 'Pedestrians are, or may be, on or near the carriageway without a marked crossing.',
    descriptionAr: 'مشاة على الطريق أو بالقرب منه دون وجود ممر مخصص.',
  },
  {
    id: 'A15', code: 'A15',
    name: 'Varning för barn',
    nameEn: 'Children near road',
    nameAr: 'أطفال قرب الطريق',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '👧',
    imageUrl: signImage('A15'),
    description: 'Barn leker nära vägen, t.ex. vid skola, förskola eller lekplats. Sänk hastigheten.',
    descriptionEn: 'Children play near the road, e.g. by a school, preschool or playground. Reduce speed.',
    descriptionAr: 'أطفال يلعبون بالقرب من الطريق، كالمدارس ودور الحضانة. خفّف السرعة.',
  },
  {
    id: 'A16', code: 'A16',
    name: 'Varning för cyklande och mopedförare',
    nameEn: 'Cyclists and mopeds ahead',
    nameAr: 'دراجات هوائية وموبيد',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚲',
    imageUrl: signImage('A16'),
    description: 'Cyklister eller mopedförare klass II korsar eller delar vägen framåt.',
    descriptionEn: 'Cyclists or class II moped riders cross or share the road ahead.',
    descriptionAr: 'دراجون أو سائقو موبيد (الفئة 2) يعبرون الطريق أو يسيرون عليه أمامك.',
  },
  {
    id: 'A19', code: 'A19',
    name: 'Varning för djur',
    nameEn: 'Animals on or near road',
    nameAr: 'حيوانات على الطريق',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🦌',
    imageUrl: signImage('A19'),
    description: 'Vilda eller lösgående djur (t.ex. älg, rådjur) kan befinna sig på vägen.',
    descriptionEn: 'Wild or loose animals (e.g. moose, deer) may be on the road.',
    descriptionAr: 'حيوانات برية أو طليقة (كالأيائل) قد تكون على الطريق.',
  },
  {
    id: 'A20', code: 'A20',
    name: 'Varning för vägarbete',
    nameEn: 'Roadworks ahead',
    nameAr: 'أعمال طرق',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🦺',
    imageUrl: signImage('A20'),
    description: 'Pågående vägarbete framåt. Iaktta försiktighet och följ tillfälliga skyltar.',
    descriptionEn: 'Roadworks in progress ahead. Take care and follow temporary signs.',
    descriptionAr: 'أعمال إنشاء جارية أمامك. كن حذراً واتبع اللافتات المؤقتة.',
  },
  {
    id: 'A22', code: 'A22',
    name: 'Varning för flerfärgssignal',
    nameEn: 'Traffic signals ahead',
    nameAr: 'إشارات مرور ضوئية أمامك',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚦',
    imageUrl: signImage('A22'),
    description: 'Trafikljus (flerfärgssignal) finns framåt vid korsning eller övergångsställe.',
    descriptionEn: 'Traffic lights (multi-colour signals) ahead at a junction or pedestrian crossing.',
    descriptionAr: 'إشارات مرورية ضوئية أمامك عند تقاطع أو معبر مشاة.',
  },
  {
    id: 'A24', code: 'A24',
    name: 'Varning för sidvind',
    nameEn: 'Strong side winds',
    nameAr: 'رياح جانبية قوية',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '💨',
    imageUrl: signImage('A24'),
    description: 'Kraftiga sidvindar kan förekomma, t.ex. vid broar, tunnelmynningar eller öppen terräng.',
    descriptionEn: 'Strong side winds may occur, e.g. at bridges, tunnel mouths or open terrain.',
    descriptionAr: 'رياح جانبية قوية محتملة عند الجسور أو مداخل الأنفاق أو المناطق المكشوفة.',
  },
  {
    id: 'A26', code: 'A26',
    name: 'Varning för tunnel',
    nameEn: 'Tunnel ahead',
    nameAr: 'نفق أمامك',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚇',
    imageUrl: signImage('A26'),
    description: 'En tunnel finns framåt. Tänd belysning, håll avstånd och iaktta hastighetsbegränsningen.',
    descriptionEn: 'A tunnel lies ahead. Switch on your lights, keep your distance and obey the speed limit.',
    descriptionAr: 'نفق أمامك. أشعل الأضواء، احتفظ بمسافة كافية والتزم بحد السرعة.',
  },
  {
    id: 'A28', code: 'A28',
    name: 'Varning för vägkorsning',
    nameEn: 'Uncontrolled road junction',
    nameAr: 'تقاطع طرق',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '✛',
    imageUrl: signImage('A28'),
    description: 'Vägkorsning utan trafikljus eller väjningspliktsmärken. Var extra uppmärksam.',
    descriptionEn: 'A road junction without traffic lights or give-way signs. Be extra alert.',
    descriptionAr: 'تقاطع طرق بدون إشارات ضوئية أو علامات أولوية. كن يقظاً بشكل خاص.',
  },
  {
    id: 'A30', code: 'A30',
    name: 'Varning för cirkulationsplats',
    nameEn: 'Roundabout ahead',
    nameAr: 'دوّار أمامك',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🔄',
    imageUrl: signImage('A30'),
    description: 'En cirkulationsplats (rondell) finns framåt. Fordonstrafik i cirkeln har företräde.',
    descriptionEn: 'A roundabout lies ahead. Traffic already in the circle has priority.',
    descriptionAr: 'دوّار (دائري) أمامك. المركبات داخل الدائري لها الأولوية.',
  },
  {
    id: 'A34', code: 'A34',
    name: 'Varning för kö',
    nameEn: 'Queue likely ahead',
    nameAr: 'احتمال ازدحام أمامك',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚗🚗',
    imageUrl: signImage('A34'),
    description: 'Köbildning förekommer eller kan förekomma framåt. Sänk hastigheten och var beredd att stanna.',
    descriptionEn: 'Queues form, or may form, ahead. Reduce speed and be ready to stop.',
    descriptionAr: 'تشكّل طابور مروري متوقع أمامك. خفّف السرعة وكن مستعداً للتوقف.',
  },
  {
    id: 'A35', code: 'A35',
    name: 'Varning för järnvägskorsning med bommar',
    nameEn: 'Level crossing with barriers',
    nameAr: 'تقاطع سكة حديد مع حواجز',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚂',
    imageUrl: signImage('A35'),
    description: 'Plankorsning med järnväg och bommar. Stanna alltid när bommar fälls ned.',
    descriptionEn: 'Level crossing with railway and barriers. Always stop when the barriers come down.',
    descriptionAr: 'تقاطع مستوٍ مع سكة حديد وحواجز. أوقف سيارتك دائماً عند إنزال الحواجز.',
  },
  {
    id: 'A36', code: 'A36',
    name: 'Varning för järnvägskorsning utan bommar',
    nameEn: 'Level crossing without barriers',
    nameAr: 'تقاطع سكة حديد بلا حواجز',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚃',
    imageUrl: signImage('A36'),
    description: 'Obevakad plankorsning utan bommar. Stanna och försäkra dig om att inget tåg är på väg.',
    descriptionEn: 'Unguarded level crossing without barriers. Stop and make sure no train is coming.',
    descriptionAr: 'تقاطع مستوٍ مع سكة حديد بدون حواجز. قف وتأكد من عدم اقتراب أي قطار.',
  },

  // ── B. VÄJNINGSPLIKTSMÄRKEN (Priority signs) ───────────────────────
  {
    id: 'B1', code: 'B1',
    name: 'Väjningsplikt',
    nameEn: 'Give way',
    nameAr: 'أعطِ الأفضلية',
    category: 'priority', shape: 'triangle', color: 'red',
    symbol: '▽',
    imageUrl: signImage('B1'),
    description: 'Du har väjningsplikt mot all trafik på den korsande vägen. Anpassa hastigheten och lämna företräde.',
    descriptionEn: 'You must give way to all traffic on the crossing road. Adjust your speed and yield.',
    descriptionAr: 'يجب عليك إفساح المجال لجميع المركبات على الطريق المتقاطع.',
  },
  {
    id: 'B2', code: 'B2',
    name: 'Stopplikt',
    nameEn: 'Stop',
    nameAr: 'قِف',
    category: 'priority', shape: 'octagon', color: 'red',
    symbol: '🛑',
    imageUrl: signImage('B2'),
    description: 'Du måste stanna helt och lämna företräde åt all korsande trafik innan du fortsätter.',
    descriptionEn: 'You must come to a complete stop and give way to all crossing traffic before continuing.',
    descriptionAr: 'يجب عليك التوقف الكامل وإعطاء الأولوية لجميع المركبات المتقاطعة قبل المتابعة.',
  },
  {
    id: 'B3', code: 'B3',
    name: 'Övergångsställe',
    nameEn: 'Pedestrian crossing',
    nameAr: 'معبر مشاة',
    category: 'priority', shape: 'square', color: 'blue',
    symbol: '🦓',
    imageUrl: signImage('B3'),
    description: 'Anger plats för övergångsställe. Fordonsförare ska lämna gående och cyklister företräde.',
    descriptionEn: 'Marks a pedestrian crossing. Drivers must give way to pedestrians and cyclists.',
    descriptionAr: 'يشير إلى موقع ممر للمشاة. على السائقين إفساح المجال للمشاة والدراجين.',
  },
  {
    id: 'B4', code: 'B4',
    name: 'Huvudled',
    nameEn: 'Priority road',
    nameAr: 'طريق ذو أولوية',
    category: 'priority', shape: 'diamond', color: 'yellow',
    symbol: '◆',
    imageUrl: signImage('B4'),
    description: 'Du befinner dig på en väg med kontinuerlig företrädesrätt. Trafik från sidovägar har väjningsplikt.',
    descriptionEn: 'You are on a road with continuous right of way. Traffic from side roads must give way.',
    descriptionAr: 'أنت على طريق ذي أولوية مستمرة. حركة المرور القادمة من الطرق الجانبية يجب أن تتوقف.',
  },
  {
    id: 'B5', code: 'B5',
    name: 'Huvudled upphör',
    nameEn: 'End of priority road',
    nameAr: 'نهاية الطريق ذي الأولوية',
    category: 'priority', shape: 'diamond', color: 'yellow',
    symbol: '◇',
    imageUrl: signImage('B5'),
    description: 'Företrädesrätten på huvudleden upphör. Du kan nu möta trafik med lika eller högre prioritet.',
    descriptionEn: 'The right of way on the main road ends. You may now meet traffic with equal or higher priority.',
    descriptionAr: 'تنتهي أولوية الطريق الرئيسي. قد تواجه مركبات ذات أولوية مساوية أو أعلى.',
  },
  {
    id: 'B6', code: 'B6',
    name: 'Väjningsplikt mot mötande trafik',
    nameEn: 'Give way to oncoming traffic',
    nameAr: 'أعطِ الأفضلية للمرور القادم من المقابل',
    category: 'priority', shape: 'square', color: 'blue',
    symbol: '↕',
    imageUrl: signImage('B6'),
    description: 'Vid smalare passager måste du vänta och låta mötande trafik passera först.',
    descriptionEn: 'At narrow passages you must wait and let oncoming traffic pass first.',
    descriptionAr: 'عند الممرات الضيقة يجب عليك الانتظار والسماح للمركبات القادمة بالمرور أولاً.',
  },
  {
    id: 'B7', code: 'B7',
    name: 'Mötande trafik har väjningsplikt',
    nameEn: 'Oncoming traffic must give way',
    nameAr: 'المرور القادم من المقابل عليه إفساح الطريق لك',
    category: 'priority', shape: 'square', color: 'blue',
    symbol: '↕',
    imageUrl: signImage('B7'),
    description: 'Mötande fordon ska vänta och lämna dig företräde vid smalare passager.',
    descriptionEn: 'Oncoming vehicles must wait and give way to you at narrow passages.',
    descriptionAr: 'المركبات القادمة يجب أن تنتظر وتعطيك الأولوية عند الممرات الضيقة.',
  },

  // ── C. FÖRBUDSMÄRKEN (Prohibition signs) ──────────────────────────
  {
    id: 'C1', code: 'C1',
    name: 'Förbud mot infart med fordon',
    nameEn: 'No entry for vehicles',
    nameAr: 'ممنوع دخول المركبات',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '⛔',
    imageUrl: signImage('C1'),
    description: 'Infart med fordon (alla slag) är absolut förbjuden i denna riktning.',
    descriptionEn: 'Entering with any kind of vehicle is strictly forbidden in this direction.',
    descriptionAr: 'الدخول بأي نوع من المركبات محظور تماماً في هذا الاتجاه.',
  },
  {
    id: 'C2', code: 'C2',
    name: 'Förbud mot trafik med fordon',
    nameEn: 'No vehicles',
    nameAr: 'ممنوع سير المركبات',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🚫',
    imageUrl: signImage('C2'),
    description: 'Trafik med fordon (i båda riktningarna) är förbjuden på denna väg eller plats.',
    descriptionEn: 'Traffic with vehicles (in both directions) is prohibited on this road or place.',
    descriptionAr: 'حركة مرور المركبات محظورة في كلا الاتجاهين على هذا الطريق أو المكان.',
  },
  {
    id: 'C7', code: 'C7',
    name: 'Förbud mot trafik med tung lastbil',
    nameEn: 'No heavy goods vehicles',
    nameAr: 'ممنوع الشاحنات الثقيلة',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🚚',
    imageUrl: signImage('C7'),
    description: 'Tunga lastbilar (totalvikt över 3,5 ton) får inte trafikera denna väg.',
    descriptionEn: 'Heavy goods vehicles (gross weight over 3.5 tonnes) may not use this road.',
    descriptionAr: 'ممنوع مرور الشاحنات الثقيلة (الوزن الإجمالي أكثر من 3.5 طن) على هذا الطريق.',
  },
  {
    id: 'C10', code: 'C10',
    name: 'Förbud mot trafik med cykel och moped klass II',
    nameEn: 'No cycles or mopeds',
    nameAr: 'ممنوع الدراجات الهوائية والموبيد (الفئة 2)',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🚲',
    imageUrl: signImage('C10'),
    description: 'Cyklar och mopeder klass II är förbjudna på denna väg. Tilläggstavla kan utvidga förbudet till moped klass I.',
    descriptionEn: 'Cycles and class II mopeds are prohibited on this road. An additional plate can extend the ban to class I mopeds.',
    descriptionAr: 'ممنوع مرور الدراجات الهوائية والموبيد (الفئة 2) على هذا الطريق.',
  },
  {
    id: 'C17', code: 'C17',
    name: 'Begränsad fordonshöjd',
    nameEn: 'Maximum vehicle height',
    nameAr: 'الحد الأقصى لارتفاع المركبة',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '↕',
    imageUrl: signImage('C17'),
    description: 'Fordon som är högre än angiven siffra (i meter) är förbjudna att passera.',
    descriptionEn: 'Vehicles taller than the figure shown (in metres) may not pass.',
    descriptionAr: 'ممنوع مرور المركبات التي يتجاوز ارتفاعها الرقم المُدوَّن على اللافتة (بالأمتار).',
  },
  {
    id: 'C25', code: 'C25',
    name: 'Förbud mot sväng i korsning',
    nameEn: 'No turning at junction',
    nameAr: 'ممنوع الانعطاف عند التقاطع',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '↩',
    imageUrl: signImage('C25'),
    description: 'Svängning i korsning är förbjuden i den riktning som anges på märket.',
    descriptionEn: 'Turning at the junction is prohibited in the direction shown on the sign.',
    descriptionAr: 'ممنوع الانعطاف في التقاطع في الاتجاه المُشار إليه على اللافتة.',
  },
  {
    id: 'C26', code: 'C26',
    name: 'Förbud mot U-sväng',
    nameEn: 'No U-turn',
    nameAr: 'ممنوع الدوران للخلف',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🔄',
    imageUrl: signImage('C26'),
    description: 'U-sväng (helomvändning) är förbjuden på denna vägsträcka.',
    descriptionEn: 'U-turns are prohibited on this stretch of road.',
    descriptionAr: 'ممنوع الدوران الكامل (استدارة U) على هذا الجزء من الطريق.',
  },
  {
    id: 'C27', code: 'C27',
    name: 'Förbud mot omkörning',
    nameEn: 'No overtaking',
    nameAr: 'ممنوع التجاوز',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🚫',
    imageUrl: signImage('C27'),
    description: 'Omkörning av motorfordon är förbjuden. Förbudet gäller till nästa korsning eller upphörsmärke.',
    descriptionEn: 'Overtaking motor vehicles is prohibited. The ban applies until the next junction or an end sign.',
    descriptionAr: 'ممنوع التجاوز. يسري الحظر حتى التقاطع التالي أو علامة الإنهاء.',
  },
  {
    id: 'C31', code: 'C31',
    name: 'Hastighetsbegränsning',
    nameEn: 'Maximum speed limit',
    nameAr: 'الحد الأقصى للسرعة',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '50',
    imageUrl: signImage('C31'),
    description: 'Den angivna siffran är högsta tillåtna hastighet i km/h. Gäller till ny hastighetsskylt eller korsning.',
    descriptionEn: 'The figure shown is the maximum permitted speed in km/h. It applies until a new speed sign or a junction.',
    descriptionAr: 'الرقم المُدوَّن هو الحد الأقصى للسرعة بـ كم/ساعة. يسري حتى لافتة سرعة أخرى أو تقاطع.',
  },
  {
    id: 'C35', code: 'C35',
    name: 'Förbud mot att parkera fordon',
    nameEn: 'No parking',
    nameAr: 'ممنوع الركن',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: 'P',
    imageUrl: signImage('C35'),
    description: 'Parkering är förbjuden på denna sida av gatan. Tilläggstavla kan ange tidsbegränsning.',
    descriptionEn: 'Parking is prohibited on this side of the street. An additional plate may set a time limit.',
    descriptionAr: 'ممنوع الوقوف على هذا الجانب من الشارع. قد تُحدّد لافتة إضافية مدة الحظر.',
  },
  {
    id: 'C39', code: 'C39',
    name: 'Förbud mot att stanna och parkera fordon',
    nameEn: 'No stopping or parking',
    nameAr: 'ممنوع التوقف والركن',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '×',
    imageUrl: signImage('C39'),
    description: 'Stannande och parkering är absolut förbjuden. Strängare än C35.',
    descriptionEn: 'Stopping and parking are strictly prohibited. Stricter than C35.',
    descriptionAr: 'التوقف والوقوف محظوران تماماً. أشد من C35.',
  },

  // ── D. PÅBUDSMÄRKEN (Mandatory signs) ─────────────────────────────
  {
    id: 'D1', code: 'D1',
    name: 'Påbjuden körriktning',
    nameEn: 'Mandatory direction of travel',
    nameAr: 'اتجاه السير إلزامي',
    category: 'mandatory', shape: 'circle', color: 'blue',
    symbol: '→',
    imageUrl: signImage('D1'),
    description: 'Fordon måste följa den riktning som pilen anger. Avvikelse är förbjuden.',
    descriptionEn: 'Vehicles must follow the direction shown by the arrow. Deviating is prohibited.',
    descriptionAr: 'يجب على المركبات اتباع الاتجاه الذي تشير إليه السهم. الانحراف عنه محظور.',
  },
  {
    id: 'D2', code: 'D2',
    name: 'Påbjuden körbana',
    nameEn: 'Keep to this side',
    nameAr: 'الزم هذا الجانب',
    category: 'mandatory', shape: 'circle', color: 'blue',
    symbol: '↗',
    imageUrl: signImage('D2'),
    description: 'Fordon får bara passera märket på den sida som pilen visar — t.ex. håll till höger om ett hinder.',
    descriptionEn: 'Vehicles may pass the sign only on the side the arrow shows — e.g. keep right of an obstacle.',
    descriptionAr: 'يجب على المركبات المرور من الجانب الذي يشير إليه السهم — مثلاً الالتزام باليمين عند عائق.',
  },
  {
    id: 'D3', code: 'D3',
    name: 'Cirkulationsplats',
    nameEn: 'Roundabout — keep circulating',
    nameAr: 'دوّار: تابِع الدوران',
    category: 'mandatory', shape: 'circle', color: 'blue',
    symbol: '↺',
    imageUrl: signImage('D3'),
    description: 'Fordonstrafik ska röra sig moturs i cirkulationsplatsen. Inkommande trafik har väjningsplikt.',
    descriptionEn: 'Traffic must move counter-clockwise in the roundabout. Entering traffic must give way.',
    descriptionAr: 'يجب على المركبات الدوران عكس عقارب الساعة في الدوّار. المركبات الداخلة يجب أن تعطي الأولوية.',
  },
  {
    id: 'D4', code: 'D4',
    name: 'Påbjuden cykelbana',
    nameEn: 'Mandatory cycle path',
    nameAr: 'مسار دراجات إلزامي',
    category: 'mandatory', shape: 'circle', color: 'blue',
    symbol: '🚴',
    imageUrl: signImage('D4'),
    description: 'Cyklister och mopedister klass II är skyldiga att använda denna bana.',
    descriptionEn: 'Cyclists and class II moped riders must use this path.',
    descriptionAr: 'الدراجون وسائقو الموبيد (الفئة 2) ملزمون باستخدام هذا المسار.',
  },
  {
    id: 'D5', code: 'D5',
    name: 'Påbjuden gångbana',
    nameEn: 'Mandatory footpath',
    nameAr: 'مسار مشاة إلزامي',
    category: 'mandatory', shape: 'circle', color: 'blue',
    symbol: '🚶',
    imageUrl: signImage('D5'),
    description: 'Gångtrafikanter ska använda denna bana. Cykeltrafik är förbjuden.',
    descriptionEn: 'Pedestrians must use this path. Cycling is prohibited.',
    descriptionAr: 'المشاة ملزمون باستخدام هذا المسار. الدراجات محظورة هنا.',
  },
  {
    id: 'D6', code: 'D6',
    name: 'Påbjuden gång- och cykelbana',
    nameEn: 'Shared mandatory path',
    nameAr: 'مسار مشترك للمشاة والدراجات',
    category: 'mandatory', shape: 'circle', color: 'blue',
    symbol: '🚶🚴',
    imageUrl: signImage('D6'),
    description: 'Gångtrafikanter och cyklister delar banan utan fysisk skiljelinje.',
    descriptionEn: 'Pedestrians and cyclists share the path without a physical dividing line.',
    descriptionAr: 'المشاة والدراجون يتشاركون نفس المسار دون فاصل مادي بينهم.',
  },

  // ── E. ANVISNINGSMÄRKEN (Information signs) ────────────────────────
  {
    id: 'E1', code: 'E1',
    name: 'Motorväg',
    nameEn: 'Motorway begins',
    nameAr: 'بداية الطريق السريع',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🛣️',
    imageUrl: signImage('E1'),
    description: 'Motorväg börjar. Särskilda regler gäller, bland annat är gång-, cykel- och mopedtrafik förbjuden.',
    descriptionEn: 'Motorway begins. Special rules apply, including a ban on pedestrians, cyclists and mopeds.',
    descriptionAr: 'بداية طريق سريع (موتورواي). تسري قواعد خاصة، منها منع المشاة والدراجات الهوائية والنارية الخفيفة.',
  },
  {
    id: 'E2', code: 'E2',
    name: 'Motorväg upphör',
    nameEn: 'End of motorway',
    nameAr: 'نهاية الطريق السريع',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🛣',
    imageUrl: signImage('E2'),
    description: 'Motorvägssträckan slutar och normala landsvägsregler återgäller.',
    descriptionEn: 'The motorway section ends and normal country-road rules apply again.',
    descriptionAr: 'نهاية الطريق السريع وتعود قواعد الطريق العادية.',
  },
  {
    id: 'E3', code: 'E3',
    name: 'Motortrafikled',
    nameEn: 'Expressway begins',
    nameAr: 'بداية طريق المركبات الآلية',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🚗',
    imageUrl: signImage('E3'),
    description: 'Motortrafikled — liknar motorväg men tillåter lägre hastighet. Gång- och cykeltrafik är förbjuden.',
    descriptionEn: 'Expressway — similar to a motorway but allows a lower speed. Pedestrians and cyclists are prohibited.',
    descriptionAr: 'طريق للسيارات فقط — يشبه الطريق السريع لكن بسرعة أقل. المشاة والدراجون محظورون.',
  },
  {
    id: 'E5', code: 'E5',
    name: 'Tättbebyggt område',
    nameEn: 'Built-up area begins',
    nameAr: 'بداية المنطقة المأهولة',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🏘️',
    imageUrl: signImage('E5'),
    description: 'Tättbebyggt område börjar. Hastighetsgränsen är normalt 50 km/h om ingen annan skylt finns.',
    descriptionEn: 'Built-up area begins. The speed limit is normally 50 km/h unless another sign says otherwise.',
    descriptionAr: 'بداية منطقة مبنية. حد السرعة عادةً 50 كم/ساعة ما لم تُشر لافتة أخرى.',
  },
  {
    id: 'E6', code: 'E6',
    name: 'Tättbebyggt område upphör',
    nameEn: 'End of built-up area',
    nameAr: 'نهاية المنطقة المأهولة',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🏘',
    imageUrl: signImage('E6'),
    description: 'Tättbebyggt område slutar. Hastighetsgränsen utanför tättbebyggt område gäller (70 km/h om inte annat anges).',
    descriptionEn: 'Built-up area ends. The speed limit outside built-up areas applies (70 km/h unless stated otherwise).',
    descriptionAr: 'نهاية المنطقة المبنية. يُطبَّق حد السرعة خارج المناطق المبنية (70 كم/ساعة ما لم يُشر إلى غير ذلك).',
  },
  {
    id: 'E7', code: 'E7',
    name: 'Gågata',
    nameEn: 'Pedestrian street',
    nameAr: 'شارع للمشاة',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🚶',
    imageUrl: signImage('E7'),
    description: 'Gågata börjar. Fordon får bara köra för att lasta/lossa och med gångfart. Fotgängare har alltid företräde.',
    descriptionEn: 'Pedestrian street begins. Vehicles may drive only to load/unload and at walking pace. Pedestrians always have priority.',
    descriptionAr: 'بداية شارع المشاة. المركبات تسير فقط للتحميل/التفريغ وبسرعة المشي. للمشاة الأولوية دائماً.',
  },
  {
    id: 'E16', code: 'E16',
    name: 'Enkelriktad trafik',
    nameEn: 'One-way traffic',
    nameAr: 'سير باتجاه واحد',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '→',
    imageUrl: signImage('E16'),
    description: 'Trafik är tillåten endast i pilens riktning. Motgående körning är förbjuden.',
    descriptionEn: 'Traffic is allowed only in the direction of the arrow. Driving against it is prohibited.',
    descriptionAr: 'حركة المرور مسموح بها في اتجاه السهم فقط. القيادة في الاتجاه المعاكس محظورة.',
  },
  {
    id: 'E19', code: 'E19',
    name: 'Parkering',
    nameEn: 'Parking place',
    nameAr: 'موقف سيارات',
    category: 'information', shape: 'square', color: 'blue',
    symbol: 'P',
    imageUrl: signImage('E19'),
    description: 'Anger en tillåten parkeringsplats eller parkeringszon. Tilläggstavla kan ange villkor.',
    descriptionEn: 'Marks a permitted parking place or parking zone. An additional plate may set conditions.',
    descriptionAr: 'يشير إلى موقف سيارات مسموح به أو منطقة وقوف. قد تُحدّد لافتة إضافية الشروط.',
  },
  {
    id: 'E22', code: 'E22',
    name: 'Busshållplats',
    nameEn: 'Bus stop',
    nameAr: 'موقف حافلات',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🚌',
    imageUrl: signImage('E22'),
    description: 'Anger en hållplats för linjetrafik och skolskjuts. Fordon får inte stanna eller parkera vid märket.',
    descriptionEn: 'Marks a stop for scheduled services and school transport. Vehicles may not stop or park at the sign.',
    descriptionAr: 'يشير إلى محطة للحافلات العامة وحافلات المدارس. ممنوع التوقف أو الوقوف عند هذه العلامة.',
  },
  {
    id: 'E26', code: 'E26',
    name: 'Tunnel',
    nameEn: 'Tunnel',
    nameAr: 'نفق',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🚇',
    imageUrl: signImage('E26'),
    description: 'Anger att en tunnel börjar. Tunnelns namn och längd anges på märket. Tänd belysning och håll avstånd.',
    descriptionEn: 'Shows that a tunnel begins. The tunnel\'s name and length are shown on the sign. Switch on your lights and keep your distance.',
    descriptionAr: 'يشير إلى بداية نفق. يُذكر اسم النفق وطوله على العلامة. أشعل الأضواء والتزم بالمسافة.',
  },

  // ── Additional signs (names from the Swedish road-sign ordinance, images public domain) ──
  {
    id: 'A3', code: 'A3',
    name: 'Varning för nedförslutning',
    nameEn: 'Steep descent ahead',
    nameAr: 'منحدر شديد أمامك',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '⬇️',
    imageUrl: signImage('A3'),
    description: 'Märket anger brant nedförslutning. Siffran anger lutningen i procent.',
    descriptionEn: 'Warns of a steep descent. The number shows the gradient as a percentage.',
    descriptionAr: 'تحذير من منحدر شديد. يبيّن الرقم نسبة الانحدار المئوية.',
  },
  {
    id: 'A4', code: 'A4',
    name: 'Varning för stigning',
    nameEn: 'Steep ascent ahead',
    nameAr: 'صعود حاد أمامك',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '⬆️',
    imageUrl: signImage('A4'),
    description: 'Märket anger kraftig stigning. Siffran anger stigningen i procent.',
    descriptionEn: 'Warns of a steep climb. The number shows the gradient as a percentage.',
    descriptionAr: 'تحذير من طريق صاعد بشدة. يبيّن الرقم نسبة الصعود المئوية.',
  },
  {
    id: 'A6', code: 'A6',
    name: 'Varning för bro',
    nameEn: 'Opening bridge ahead',
    nameAr: 'جسر متحرك أمامك',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🌉',
    imageUrl: signImage('A6'),
    description: 'Märket anger en öppningsbar bro.',
    descriptionEn: 'Warns of a bridge that can open.',
    descriptionAr: 'تحذير من جسر قابل للفتح (جسر متحرك).',
  },
  {
    id: 'A7', code: 'A7',
    name: 'Varning för kaj',
    nameEn: 'Road ends at water',
    nameAr: 'الطريق ينتهي عند الماء',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '⚓',
    imageUrl: signImage('A7'),
    description: 'Märket anger en plats där vägen slutar mot vatten.',
    descriptionEn: 'Marks a place where the road ends at open water.',
    descriptionAr: 'يشير إلى مكان ينتهي فيه الطريق عند الماء.',
  },
  {
    id: 'A11', code: 'A11',
    name: 'Varning för stenskott',
    nameEn: 'Risk of loose chippings',
    nameAr: 'خطر تطاير الحصى',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🪨',
    imageUrl: signImage('A11'),
    description: 'Märket anger risk för stenskott. Används inte på grusväg.',
    descriptionEn: 'Warns of a risk of loose stones thrown up by traffic. Not used on gravel roads.',
    descriptionAr: 'تحذير من خطر تطاير الحصى. لا يُستخدم على الطرق الحصوية.',
  },
  {
    id: 'A17', code: 'A17',
    name: 'Varning för skidåkare',
    nameEn: 'Skiers crossing',
    nameAr: 'متزلجون يعبرون الطريق',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '⛷️',
    imageUrl: signImage('A17'),
    description: 'Märket anger en plats där skidåkare ofta korsar eller uppehåller sig på vägen.',
    descriptionEn: 'Marks a place where skiers often cross or use the road.',
    descriptionAr: 'يشير إلى مكان يعبر فيه المتزلجون الطريق أو يتواجدون عليه كثيرًا.',
  },
  {
    id: 'A18', code: 'A18',
    name: 'Varning för ridande',
    nameEn: 'Riders on the road',
    nameAr: 'خيّالة على الطريق',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🐎',
    imageUrl: signImage('A18'),
    description: 'Märket anger en vägsträcka där ridande ofta korsar eller uppehåller sig på vägen.',
    descriptionEn: 'Marks a stretch where riders often cross or use the road.',
    descriptionAr: 'يشير إلى مقطع يعبر فيه راكبو الخيل الطريق أو يتواجدون عليه كثيرًا.',
  },
  {
    id: 'A37', code: 'A37',
    name: 'Korsning med spårväg',
    nameEn: 'Tram crossing ahead',
    nameAr: 'تقاطع مع خط ترام',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚋',
    imageUrl: signImage('A37'),
    description: 'Märket varnar för en korsning med spårväg.',
    descriptionEn: 'Warns of a crossing with a tramway.',
    descriptionAr: 'تحذير من تقاطع مع خط ترام.',
  },
  {
    id: 'A41', code: 'A41',
    name: 'Varning för olycka',
    nameEn: 'Accident ahead',
    nameAr: 'حادث أمامك',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚨',
    imageUrl: signImage('A41'),
    description: 'Märket varnar för en olycka på vägen framför dig.',
    descriptionEn: 'Warns of an accident on the road ahead.',
    descriptionAr: 'تحذير من وجود حادث على الطريق أمامك.',
  },
  {
    id: 'C5', code: 'C5',
    name: 'Förbud mot trafik med motorcykel och moped klass I',
    nameEn: 'No motorcycles or class I mopeds',
    nameAr: 'ممنوع الدراجات النارية والموبيد (الفئة 1)',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🏍️',
    imageUrl: signImage('C5'),
    description: 'Förbjuder trafik med motorcykel och moped klass I.',
    descriptionEn: 'Prohibits motorcycles and class I mopeds.',
    descriptionAr: 'يمنع سير الدراجات النارية والموبيد (الفئة 1).',
  },
  {
    id: 'C6', code: 'C6',
    name: 'Förbud mot trafik med motordrivet fordon med tillkopplad släpvagn',
    nameEn: 'No vehicles with a trailer',
    nameAr: 'ممنوع المركبات ذات المقطورة',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🚚',
    imageUrl: signImage('C6'),
    description: 'Förbjuder trafik med motordrivet fordon som har en släpvagn tillkopplad.',
    descriptionEn: 'Prohibits motor vehicles with a trailer attached.',
    descriptionAr: 'يمنع سير المركبات الآلية التي تجرّ مقطورة.',
  },
  {
    id: 'C8', code: 'C8',
    name: 'Förbud mot trafik med traktor och motorredskap',
    nameEn: 'No tractors or motor implements',
    nameAr: 'ممنوع الجرارات والآليات ذاتية الحركة',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🚜',
    imageUrl: signImage('C8'),
    description: 'Förbjuder trafik med traktor och motorredskap.',
    descriptionEn: 'Prohibits tractors and motor implements.',
    descriptionAr: 'يمنع سير الجرارات والآليات ذاتية الحركة.',
  },
  {
    id: 'C9', code: 'C9',
    name: 'Förbud mot fordon lastade med farligt gods',
    nameEn: 'No vehicles carrying dangerous goods',
    nameAr: 'ممنوع المركبات المحمّلة بمواد خطرة',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '☣️',
    imageUrl: signImage('C9'),
    description: 'Förbjuder fordon som är lastade med farligt gods.',
    descriptionEn: 'Prohibits vehicles loaded with dangerous goods.',
    descriptionAr: 'يمنع مرور المركبات المحمّلة بمواد خطرة.',
  },
  {
    id: 'C12', code: 'C12',
    name: 'Förbud mot trafik med hästfordon',
    nameEn: 'No horse-drawn vehicles',
    nameAr: 'ممنوع العربات التي تجرّها الخيول',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🐴',
    imageUrl: signImage('C12'),
    description: 'Förbjuder trafik med hästfordon.',
    descriptionEn: 'Prohibits horse-drawn vehicles.',
    descriptionAr: 'يمنع سير العربات التي تجرّها الخيول.',
  },
  {
    id: 'C14', code: 'C14',
    name: 'Förbud mot ridning',
    nameEn: 'No riding',
    nameAr: 'ممنوع ركوب الخيل',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🏇',
    imageUrl: signImage('C14'),
    description: 'Förbjuder ridning på vägen.',
    descriptionEn: 'Prohibits horse riding on the road.',
    descriptionAr: 'يمنع ركوب الخيل على الطريق.',
  },
  {
    id: 'C15', code: 'C15',
    name: 'Förbud mot gångtrafik',
    nameEn: 'No pedestrians',
    nameAr: 'ممنوع سير المشاة',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🚷',
    imageUrl: signImage('C15'),
    description: 'Förbjuder gångtrafik.',
    descriptionEn: 'Prohibits pedestrians.',
    descriptionAr: 'يمنع سير المشاة.',
  },
  {
    id: 'C18', code: 'C18',
    name: 'Begränsad längd på fordon eller fordonståg',
    nameEn: 'Maximum length of vehicle or combination',
    nameAr: 'الحد الأقصى لطول المركبة',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '📏',
    imageUrl: signImage('C18'),
    description: 'Anger högsta tillåtna längd för fordon eller fordonståg. Längden anges på märket.',
    descriptionEn: 'Sets the maximum permitted length of a vehicle or vehicle combination, shown on the sign.',
    descriptionAr: 'يبيّن أقصى طول مسموح للمركبة أو لمجموعة مركبات، ويُكتب الطول على اللافتة.',
  },
  {
    id: 'C28', code: 'C28',
    name: 'Slut på omkörningsförbud',
    nameEn: 'End of no overtaking',
    nameAr: 'نهاية منع التجاوز',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🔚',
    imageUrl: signImage('C28'),
    description: 'Anger att omkörningsförbudet upphör.',
    descriptionEn: 'Shows that the overtaking ban ends.',
    descriptionAr: 'يبيّن انتهاء منع التجاوز.',
  },
  {
    id: 'C29', code: 'C29',
    name: 'Omkörning med lastbil förbjuden',
    nameEn: 'No overtaking for trucks',
    nameAr: 'ممنوع تجاوز الشاحنات',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🚛',
    imageUrl: signImage('C29'),
    description: 'Förbjuder omkörning med lastbil.',
    descriptionEn: 'Prohibits overtaking by trucks.',
    descriptionAr: 'يمنع الشاحنات من التجاوز.',
  },
  {
    id: 'D8', code: 'D8',
    name: 'Påbjuden ridväg',
    nameEn: 'Mandatory bridleway',
    nameAr: 'مسار خيول إلزامي',
    category: 'mandatory', shape: 'circle', color: 'blue',
    symbol: '🐎',
    imageUrl: signImage('D8'),
    description: 'Anger en väg som ridande ska använda.',
    descriptionEn: 'Marks a route that riders must use.',
    descriptionAr: 'يبيّن طريقًا يجب على راكبي الخيل استخدامه.',
  },
  {
    id: 'E4', code: 'E4',
    name: 'Motortrafikled upphör',
    nameEn: 'End of expressway',
    nameAr: 'نهاية طريق المركبات الآلية',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🔚',
    imageUrl: signImage('E4'),
    description: 'Anger var motortrafikleden upphör.',
    descriptionEn: 'Shows where the expressway ends.',
    descriptionAr: 'يبيّن نهاية طريق المركبات الآلية.',
  },
  {
    id: 'E8', code: 'E8',
    name: 'Gågata upphör',
    nameEn: 'End of pedestrian street',
    nameAr: 'نهاية شارع المشاة',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🚶',
    imageUrl: signImage('E8'),
    description: 'Anger var gågatan upphör.',
    descriptionEn: 'Shows where the pedestrian street ends.',
    descriptionAr: 'يبيّن نهاية شارع المشاة.',
  },
  {
    id: 'E9', code: 'E9',
    name: 'Gångfartsområde',
    nameEn: 'Living street',
    nameAr: 'شارع سكني مشترك',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🏘️',
    imageUrl: signImage('E9'),
    description: 'Anger början på ett gångfartsområde. Fordon ska köras i gångfart.',
    descriptionEn: 'Marks the start of a living street. Vehicles must drive at walking pace.',
    descriptionAr: 'يبيّن بداية شارع سكني مشترك. يجب أن تسير المركبات بسرعة المشي.',
  },
  {
    id: 'E10', code: 'E10',
    name: 'Gångfartsområde upphör',
    nameEn: 'End of living street',
    nameAr: 'نهاية الشارع السكني المشترك',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🏘️',
    imageUrl: signImage('E10'),
    description: 'Anger var gångfartsområdet upphör.',
    descriptionEn: 'Shows where the living street ends.',
    descriptionAr: 'يبيّن نهاية الشارع السكني المشترك.',
  },
  {
    id: 'E18', code: 'E18',
    name: 'Mötesplats',
    nameEn: 'Passing place',
    nameAr: 'مكان تلاقي المركبات',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '↔️',
    imageUrl: signImage('E18'),
    description: 'Anger en plats där fordon kan mötas på en smal väg.',
    descriptionEn: 'Marks a place where vehicles can pass each other on a narrow road.',
    descriptionAr: 'يبيّن مكانًا يمكن أن تتلاقى فيه المركبات على طريق ضيق.',
  },
  {
    id: 'E23', code: 'E23',
    name: 'Taxi',
    nameEn: 'Taxi rank',
    nameAr: 'موقف سيارات الأجرة',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '🚕',
    imageUrl: signImage('E23'),
    description: 'Anger en taxistation.',
    descriptionEn: 'Marks a taxi rank.',
    descriptionAr: 'يبيّن موقفًا لسيارات الأجرة.',
  },
  {
    id: 'E25', code: 'E25',
    name: 'Betalväg',
    nameEn: 'Toll road',
    nameAr: 'طريق برسوم',
    category: 'information', shape: 'square', color: 'blue',
    symbol: '💰',
    imageUrl: signImage('E25'),
    description: 'Anger en väg där vägavgift tas ut.',
    descriptionEn: 'Marks a road where a toll is charged.',
    descriptionAr: 'يبيّن طريقًا تُفرض عليه رسوم مرور.',
  },
  {
    id: 'A21', code: 'A21',
    name: 'Slut på sträcka med vägarbete',
    nameEn: 'End of roadworks',
    nameAr: 'نهاية أعمال الطرق',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '🚧',
    imageUrl: signImage('A21'),
    description: 'Märket anger slut på en vägsträcka med vägarbete som markerats med märke A20.',
    descriptionEn: 'Marks the end of a road stretch with roadworks signed with A20.',
    descriptionAr: 'يبيّن نهاية مقطع أعمال الطرق الذي بدأ بلافتة أعمال الطرق (A20).',
  },
  {
    id: 'A25', code: 'A25',
    name: 'Varning för mötande trafik',
    nameEn: 'Oncoming traffic ahead',
    nameAr: 'مرور قادم من الاتجاه المعاكس',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '↔️',
    imageUrl: signImage('A25'),
    description: 'Märket anger att en körbana med enkelriktad trafik övergår i en körbana med trafik i båda riktningarna.',
    descriptionEn: 'Shows that a one-way carriageway changes into one with traffic in both directions.',
    descriptionAr: 'يبيّن أن مسارًا باتجاه واحد يتحول إلى مسار بالاتجاهين.',
  },
  {
    id: 'A27', code: 'A27',
    name: 'Varning för svag vägkant eller hög körbanekant',
    nameEn: 'Weak road edge or high carriageway edge',
    nameAr: 'حافة طريق ضعيفة أو حافة مرتفعة',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '⚠️',
    imageUrl: signImage('A27'),
    description: 'Märket varnar för svag vägkant eller hög körbanekant.',
    descriptionEn: 'Warns of a weak road edge or a high carriageway edge.',
    descriptionAr: 'تحذير من حافة طريق ضعيفة أو حافة مسار مرتفعة.',
  },
  {
    id: 'A40', code: 'A40',
    name: 'Varning för annan fara',
    nameEn: 'Other danger ahead',
    nameAr: 'خطر آخر أمامك',
    category: 'warning', shape: 'triangle', color: 'red',
    symbol: '❗',
    imageUrl: signImage('A40'),
    description: 'Märket varnar för annan fara. Farans art anges på en tilläggstavla.',
    descriptionEn: 'Warns of another danger. The nature of the danger is shown on an additional plate.',
    descriptionAr: 'تحذير من خطر آخر. يُذكر نوع الخطر على لافتة إضافية.',
  },
  {
    id: 'C4', code: 'C4',
    name: 'Förbud mot trafik med motordrivet fordon som har flera hjul än två',
    nameEn: 'No motor vehicles with more than two wheels',
    nameAr: 'ممنوع المركبات الآلية ذات أكثر من عجلتين',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🚗',
    imageUrl: signImage('C4'),
    description: 'Förbjuder trafik med motordrivet fordon som har flera hjul än två.',
    descriptionEn: 'Prohibits motor vehicles with more than two wheels.',
    descriptionAr: 'يمنع سير المركبات الآلية التي لها أكثر من عجلتين.',
  },
  {
    id: 'C13', code: 'C13',
    name: 'Förbud mot trafik med terrängmotorfordon och terrängsläp',
    nameEn: 'No off-road motor vehicles or trailers',
    nameAr: 'ممنوع مركبات الطرق الوعرة ومقطوراتها',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🏔️',
    imageUrl: signImage('C13'),
    description: 'Förbjuder trafik med terrängmotorfordon och terrängsläp.',
    descriptionEn: 'Prohibits off-road motor vehicles and off-road trailers.',
    descriptionAr: 'يمنع سير مركبات الطرق الوعرة ومقطوراتها.',
  },
  {
    id: 'C16', code: 'C16',
    name: 'Begränsad fordonsbredd',
    nameEn: 'Maximum vehicle width',
    nameAr: 'الحد الأقصى لعرض المركبة',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '↔️',
    imageUrl: signImage('C16'),
    description: 'Anger högsta tillåtna bredd för fordon. Bredden anges på märket.',
    descriptionEn: 'Sets the maximum permitted vehicle width, shown on the sign.',
    descriptionAr: 'يبيّن أقصى عرض مسموح للمركبة، ويُكتب العرض على اللافتة.',
  },
  {
    id: 'C19', code: 'C19',
    name: 'Minsta avstånd mellan motordrivna fordon',
    nameEn: 'Minimum distance between vehicles',
    nameAr: 'الحد الأدنى للمسافة بين المركبات',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '↔️',
    imageUrl: signImage('C19'),
    description: 'Anger minsta tillåtna avstånd mellan motordrivna fordon. Avståndet anges på märket.',
    descriptionEn: 'Sets the minimum permitted distance between motor vehicles, shown on the sign.',
    descriptionAr: 'يبيّن أدنى مسافة مسموحة بين المركبات الآلية، وتُكتب المسافة على اللافتة.',
  },
  {
    id: 'C20', code: 'C20',
    name: 'Begränsad bruttovikt på fordon',
    nameEn: 'Maximum gross weight',
    nameAr: 'الحد الأقصى للوزن الإجمالي للمركبة',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '⚖️',
    imageUrl: signImage('C20'),
    description: 'Anger högsta tillåtna bruttovikt för fordon. Vikten anges på märket.',
    descriptionEn: 'Sets the maximum permitted gross weight for vehicles, shown on the sign.',
    descriptionAr: 'يبيّن أقصى وزن إجمالي مسموح للمركبة، ويُكتب الوزن على اللافتة.',
  },
  {
    id: 'C30', code: 'C30',
    name: 'Slut på omkörningsförbud för lastbil',
    nameEn: 'End of no overtaking for trucks',
    nameAr: 'نهاية منع تجاوز الشاحنات',
    category: 'prohibition', shape: 'circle', color: 'red',
    symbol: '🔚',
    imageUrl: signImage('C30'),
    description: 'Anger att förbudet mot omkörning med lastbil upphör.',
    descriptionEn: 'Shows that the ban on overtaking by trucks ends.',
    descriptionAr: 'يبيّن انتهاء منع تجاوز الشاحنات.',
  },
  {
    id: 'D10', code: 'D10',
    name: 'Påbjudet körfält eller körbana för fordon i linjetrafik med flera',
    nameEn: 'Mandatory lane or carriageway for scheduled services and others',
    nameAr: 'مسار أو طريق إلزامي لمركبات النقل العام المنتظم وغيرها',
    category: 'mandatory', shape: 'circle', color: 'blue',
    symbol: '🚌',
    imageUrl: signImage('D10'),
    description: 'Anger början på ett körfält som är avsett för fordon i linjetrafik.',
    descriptionEn: 'Marks the start of a lane reserved for scheduled (public transport) services.',
    descriptionAr: 'يبيّن بداية مسار مخصص لمركبات النقل العام المنتظم.',
  },
  // ── T. TILLÄGGSTAVLOR (Additional plates) — verified names, public-domain images ──
  {
    id: 'T3', code: 'T3',
    name: 'Avstånd till stopplikt',
    nameEn: 'Distance to stop obligation',
    nameAr: 'المسافة إلى نقطة التوقف الإلزامي',
    category: 'additional', shape: 'square', color: 'white',
    symbol: '➕',
    imageUrl: signImage('T3'),
    description: 'Tilläggstavla som anger avståndet till en stopplikt.',
    descriptionEn: 'Additional plate showing the distance to a stop obligation.',
    descriptionAr: 'لافتة إضافية تبيّن المسافة إلى نقطة التوقف الإلزامي (قِف).',
  },
  {
    id: 'T4', code: 'T4',
    name: 'Fri bredd',
    nameEn: 'Clear width',
    nameAr: 'العرض الحرّ المتاح',
    category: 'additional', shape: 'square', color: 'white',
    symbol: '➕',
    imageUrl: signImage('T4'),
    description: 'Tilläggstavla som anger fri bredd, till exempel vid en trång passage.',
    descriptionEn: 'Additional plate showing the clear (usable) width, e.g. at a narrow passage.',
    descriptionAr: 'لافتة إضافية تبيّن العرض الحرّ المتاح، مثلًا عند ممر ضيق.',
  },
  {
    id: 'T5', code: 'T5',
    name: 'Totalvikt',
    nameEn: 'Total weight',
    nameAr: 'الوزن الإجمالي',
    category: 'additional', shape: 'square', color: 'white',
    symbol: '➕',
    imageUrl: signImage('T5'),
    description: 'Tilläggstavla som anger totalvikt.',
    descriptionEn: 'Additional plate showing a total (gross) weight.',
    descriptionAr: 'لافتة إضافية تبيّن الوزن الإجمالي.',
  },
  {
    id: 'T6', code: 'T6',
    name: 'Tidsangivelse',
    nameEn: 'Times when the prohibition applies',
    nameAr: 'أوقات سريان المنع',
    category: 'additional', shape: 'square', color: 'white',
    symbol: '➕',
    imageUrl: signImage('T6'),
    description: 'Tilläggstavla som anger vilka klockslag ett förbud gäller.',
    descriptionEn: 'Additional plate showing the times of day when a prohibition applies.',
    descriptionAr: 'لافتة إضافية تبيّن الساعات التي يسري فيها المنع.',
  },
  {
    id: 'T14', code: 'T14',
    name: 'Flervägsstopp',
    nameEn: 'All-way stop',
    nameAr: 'قِف من جميع الاتجاهات',
    category: 'additional', shape: 'square', color: 'white',
    symbol: '➕',
    imageUrl: signImage('T14'),
    description: 'Tilläggstavla som anger flervägsstopp, där alla trafikanter måste stanna.',
    descriptionEn: 'Additional plate for an all-way stop, where every approach must stop.',
    descriptionAr: 'لافتة إضافية لتقاطع «قِف» من جميع الاتجاهات، حيث يجب أن تتوقف كل المداخل.',
  },
];

/** What the app shows and plays with: every sign that has its official image. */
export const TRAFFIC_SIGNS: TrafficSign[] = splitSigns(ALL_SIGNS).playable;

export const CATEGORY_LABELS: Record<string, string> = {
  all: 'Alla märken',
  warning: 'Varningsmärken',
  prohibition: 'Förbudsmärken',
  mandatory: 'Påbudsmärken',
  priority: 'Väjningsmärken',
  information: 'Anvisningsmärken',
  additional: 'Tilläggstavlor',
};

export const CATEGORY_COLORS: Record<string, string> = {
  warning: 'bg-amber-500',
  prohibition: 'bg-red-500',
  mandatory: 'bg-blue-500',
  priority: 'bg-yellow-500',
  information: 'bg-sky-500',
  additional: 'bg-slate-500',
};
